### ISSUE TITLE
heartbeats due to Error

### ISSUE THREAD

**Issue by taoqf** [celery/py-amqp#122]
If I use Hearbeats, I see this Error when timeout.
```bash
2016-12-21 10:59:13,954 - CRITICAL - [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "./server.py", line 125, in <module>
    main()
  File "./server.py", line 121, in main
    channel.close()
  File "/home/user/anaconda3/lib/python3.5/site-packages/amqp/channel.py", line 178, in close
    self._send_method((20, 40), args)
  File "/home/user/anaconda3/lib/python3.5/site-packages/amqp/abstract_channel.py", line 56, in _send_method
    self.channel_id, method_sig, args, content,
  File "/home/user/anaconda3/lib/python3.5/site-packages/amqp/method_framing.py", line 221, in write_method
    write_frame(1, channel, payload)
  File "/home/user/anaconda3/lib/python3.5/site-packages/amqp/transport.py", line 182, in write_frame
    frame_type, channel, size, payload, 0xce,
BrokenPipeError: [Errno 32] Broken pipe
```
I use amqp like this:
```python
def main():
	connection = amqp.Connection(host = '127.0.0.1:5672', heartbeat = 1)

	channel = connection.channel()

	queue = channel.queue_declare(queue = 'myqueue', durable = True, auto_delete = False)
	queue_name = queue.queue
	channel.exchange_declare('myex', type='direct', durable = True, auto_delete = False)

	channel.queue_bind(queue_name, 'myex', 'myroutingkey')
	channel.basic_qos(prefetch_size = 0, prefetch_count = 2, a_global = False)
	channel.basic_consume(callback = __on_message, queue = queue_name)

	try:
		while True:
			connection.drain_events()
	except KeyboardInterrupt:
		logging.info("Python service stoped...........^v^")
		# Someone pressed CTRL-C, stop consuming and close
	except Exception as ex:
		logging.critical(ex)
	finally:
		channel.close()
		connection.close()
```

**Comment by taoqf** [comment]
@ask
