### ISSUE TITLE
Unrecoverable error: TypeError("Can't convert 'bytes' object to str implicitly",)

### ISSUE THREAD

**Issue by wooyek** [celery/py-amqp#155]
There seems to be a problem with worker startup on python 3.6.

```
[2017-07-12 22:02:08,311: CRITICAL/MainProcess] Unrecoverable error: TypeError("Can't convert 'bytes' object to str implicitly",)
Traceback (most recent call last):
  File "/media/data/work/your-hr/fast-rate/.pve/src/celery/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/media/data/work/your-hr/fast-rate/.pve/src/celery/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/media/data/work/your-hr/fast-rate/.pve/src/celery/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/media/data/work/your-hr/fast-rate/.pve/src/celery/celery/worker/consumer/consumer.py", line 320, in start
    blueprint.start(self)
  File "/media/data/work/your-hr/fast-rate/.pve/src/celery/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/media/data/work/your-hr/fast-rate/.pve/src/celery/celery/worker/consumer/connection.py", line 21, in start
    c.connection = c.connect()
  File "/media/data/work/your-hr/fast-rate/.pve/src/celery/celery/worker/consumer/consumer.py", line 407, in connect
    conn = self.connection_for_read(heartbeat=self.amqheartbeat)
  File "/media/data/work/your-hr/fast-rate/.pve/src/celery/celery/worker/consumer/consumer.py", line 414, in connection_for_read
    self.app.connection_for_read(heartbeat=heartbeat))
  File "/media/data/work/your-hr/fast-rate/.pve/src/celery/celery/worker/consumer/consumer.py", line 438, in ensure_connected
    callback=maybe_shutdown,
  File "/home/janusz/work/your-hr/fast-rate/.pve/lib/python3.5/site-packages/kombu/connection.py", line 405, in ensure_connection
    callback)
  File "/home/janusz/work/your-hr/fast-rate/.pve/lib/python3.5/site-packages/kombu/utils/functional.py", line 333, in retry_over_time
    return fun(*args, **kwargs)
  File "/home/janusz/work/your-hr/fast-rate/.pve/lib/python3.5/site-packages/kombu/connection.py", line 261, in connect
    return self.connection
  File "/home/janusz/work/your-hr/fast-rate/.pve/lib/python3.5/site-packages/kombu/connection.py", line 802, in connection
    self._connection = self._establish_connection()
  File "/home/janusz/work/your-hr/fast-rate/.pve/lib/python3.5/site-packages/kombu/connection.py", line 757, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/janusz/work/your-hr/fast-rate/.pve/lib/python3.5/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/home/janusz/work/your-hr/fast-rate/.pve/lib/python3.5/site-packages/amqp/connection.py", line 302, in connect
    self.drain_events(timeout=self.connect_timeout)
  File "/home/janusz/work/your-hr/fast-rate/.pve/lib/python3.5/site-packages/amqp/connection.py", line 483, in drain_events
    while not self.blocking_read(timeout):
  File "/home/janusz/work/your-hr/fast-rate/.pve/lib/python3.5/site-packages/amqp/connection.py", line 489, in blocking_read
    return self.on_inbound_frame(frame)
  File "/home/janusz/work/your-hr/fast-rate/.pve/lib/python3.5/site-packages/amqp/method_framing.py", line 69, in on_frame
    callback(channel, method_sig, buf, None)
  File "/home/janusz/work/your-hr/fast-rate/.pve/lib/python3.5/site-packages/amqp/connection.py", line 493, in on_inbound_method
    method_sig, payload, content,
  File "/home/janusz/work/your-hr/fast-rate/.pve/lib/python3.5/site-packages/amqp/abstract_channel.py", line 142, in dispatch_method
    listener(*args)
  File "/home/janusz/work/your-hr/fast-rate/.pve/lib/python3.5/site-packages/amqp/connection.py", line 347, in _on_start
    self.mechanisms = mechanisms.split(b' ')
```

```
argsig = {str} 'FsSs'
client_properties = {dict} {'product': 'py-amqp', 'product_version': '2.2.0'}
locales = {str} 'en_US'
mechanisms = {str} 'PLAIN AMQPLAIN'
self = {Connection} <kombu.transport.pyamqp.Connection object at 0x7f32c912f2e8>
server_properties = {dict} {'version': '3.5.8', 'platform': 'Erlang/OTP', 'cluster_name': 'antelope', 'information': 'Licensed under the MPL.  See http://www.rabbitmq.com/', 'capabilities': {'consumer_cancel_notify': True, 'publisher_confirms': True, 'per_consumer_qos': True, 'conne
version_major = {int} 0
version_minor = {int} 9
server_properties = {dict} {'version': '3.5.8', 'platform': 'Erlang/OTP', 'cluster_name': 'antelope', 
```

**Comment by lcd1232** [comment]
@wooyek add this at line 347
```
...
self.server_properties = server_properties
if isinstance(mechanisms, str):
    mechanisms = mechanisms.encode()
self.mechanisms = mechanisms.split(b' ')
...
```

**Comment by wooyek** [comment]
Thx, I freezed amqp==2.1.4 and it's ok. 

I already install Celery from `master` to overcome celery/celery#3620. I don't wan't to create another fork.

**Comment by Arun-KumarH** [comment]
Even I am getting the same error (during creation of MessageQueue on startup) inside the docker container and we do not have control to point to the AMQP 2.1.4 version here.
Could you please let us know when the fix would be available ?

```
{"log":"  File \"/pyenv/lib/python3.4/site-packages/kombu/connection.py\", line 736, in SimpleQueue\r\n","stream":"stdout","time":"2017-07-13T11:04:21.318357708Z"}
{"log":"    exchange_opts, **kwargs)\r\n","stream":"stdout","time":"2017-07-13T11:04:21.319390016Z"}
{"log":"  File \"/pyenv/lib/python3.4/site-packages/kombu/simple.py\", line 118, in __init__\r\n","stream":"stdout","time":"2017-07-13T11:04:21.319411846Z"}
{"log":"    consumer = messaging.Consumer(channel, queue)\r\n","stream":"stdout","time":"2017-07-13T11:04:21.320005643Z"}
{"log":"  File \"/pyenv/lib/python3.4/site-packages/kombu/messaging.py\", line 386, in __init__\r\n","stream":"stdout","time":"2017-07-13T11:04:21.320078665Z"}
{"log":"    self.revive(self.channel)\r\n","stream":"stdout","time":"2017-07-13T11:04:21.320828287Z"}
{"log":"  File \"/pyenv/lib/python3.4/site-packages/kombu/messaging.py\", line 399, in revive\r\n","stream":"stdout","time":"2017-07-13T11:04:21.320844347Z"}
{"log":"    channel = self.channel = maybe_channel(channel)\r\n","stream":"stdout","time":"2017-07-13T11:04:21.321310318Z"}
{"log":"  File \"/pyenv/lib/python3.4/site-packages/kombu/connection.py\", line 973, in maybe_channel\r\n","stream":"stdout","time":"2017-07-13T11:04:21.321324115Z"}
{"log":"    return channel.default_channel\r\n","stream":"stdout","time":"2017-07-13T11:04:21.322061234Z"}
{"log":"  File \"/pyenv/lib/python3.4/site-packages/kombu/connection.py\", line 819, in default_channel\r\n","stream":"stdout","time":"2017-07-13T11:04:21.322076112Z"}
{"log":"    self.connection\r\n","stream":"stdout","time":"2017-07-13T11:04:21.322696738Z"}
{"log":"  File \"/pyenv/lib/python3.4/site-packages/kombu/connection.py\", line 802, in connection\r\n","stream":"stdout","time":"2017-07-13T11:04:21.322709669Z"}
{"log":"    self._connection = self._establish_connection()\r\n","stream":"stdout","time":"2017-07-13T11:04:21.323307023Z"}
{"log":"  File \"/pyenv/lib/python3.4/site-packages/kombu/connection.py\", line 757, in _establish_connection\r\n","stream":"stdout","time":"2017-07-13T11:04:21.323320332Z"}
{"log":"    conn = self.transport.establish_connection()\r\n","stream":"stdout","time":"2017-07-13T11:04:21.323897159Z"}
{"log":"  File \"/pyenv/lib/python3.4/site-packages/kombu/transport/pyamqp.py\", line 130, in establish_connection\r\n","stream":"stdout","time":"2017-07-13T11:04:21.323910843Z"}
{"log":"    conn.connect()\r\n","stream":"stdout","time":"2017-07-13T11:04:21.324420272Z"}
{"log":"  File \"/pyenv/lib/python3.4/site-packages/amqp/connection.py\", line 302, in connect\r\n","stream":"stdout","time":"2017-07-13T11:04:21.324433318Z"}
{"log":"    self.drain_events(timeout=self.connect_timeout)\r\n","stream":"stdout","time":"2017-07-13T11:04:21.325071959Z"}
{"log":"  File \"/pyenv/lib/python3.4/site-packages/amqp/connection.py\", line 483, in drain_events\r\n","stream":"stdout","time":"2017-07-13T11:04:21.325107319Z"}
{"log":"    while not self.blocking_read(timeout):\r\n","stream":"stdout","time":"2017-07-13T11:04:21.325584621Z"}
{"log":"  File \"/pyenv/lib/python3.4/site-packages/amqp/connection.py\", line 489, in blocking_read\r\n","stream":"stdout","time":"2017-07-13T11:04:21.325597622Z"}
{"log":"    return self.on_inbound_frame(frame)\r\n","stream":"stdout","time":"2017-07-13T11:04:21.326055623Z"}
{"log":"  File \"/pyenv/lib/python3.4/site-packages/amqp/method_framing.py\", line 69, in on_frame\r\n","stream":"stdout","time":"2017-07-13T11:04:21.326068205Z"}
{"log":"    callback(channel, method_sig, buf, None)\r\n","stream":"stdout","time":"2017-07-13T11:04:21.326551848Z"}
{"log":"  File \"/pyenv/lib/python3.4/site-packages/amqp/connection.py\", line 493, in on_inbound_method\r\n","stream":"stdout","time":"2017-07-13T11:04:21.326665366Z"}
{"log":"    method_sig, payload, content,\r\n","stream":"stdout","time":"2017-07-13T11:04:21.327077631Z"}
{"log":"  File \"/pyenv/lib/python3.4/site-packages/amqp/abstract_channel.py\", line 142, in dispatch_method\r\n","stream":"stdout","time":"2017-07-13T11:04:21.327090259Z"}
{"log":"    listener(*args)\r\n","stream":"stdout","time":"2017-07-13T11:04:21.327557632Z"}
{"log":"  File \"/pyenv/lib/python3.4/site-packages/amqp/connection.py\", line 347, in _on_start\r\n","stream":"stdout","time":"2017-07-13T11:04:21.327570893Z"}
{"log":"    self.mechanisms = mechanisms.split(b' ')\r\n","stream":"stdout","time":"2017-07-13T11:04:21.327959504Z"}
{"log":"TypeError: Can't convert 'bytes' object to str implicitly\r\n","stream":"stdout","time":"2017-07-13T11:04:21.328062662Z"}
```

**Comment by erinaceous** [comment]
@Arun-KumarH I encountered this issue today, for now you can monkey-patch the _on_start function somewhere in your own code, before anything initializes an amqp connection:

    import amqp
    amqp.connection.Connection._old_on_start = amqp.connection.Connection._on_start
    def monkey_patched_on_start(
            self, version_major, version_minor, server_properties,
            mechanisms, locales, argsig='FsSs'
    ):
        if isinstance(mechanisms, str):
            mechanisms = mechanisms.encode()
    
        return self._old_on_start(
            version_major, version_minor, server_properties,
            mechanisms, locales, argsig
        )
    amqp.connection.Connection._on_start = monkey_patched_on_start

**Comment by auvipy** [comment]
can you investigate using git blame?

**Comment by jacumol** [comment]
Hello @Arun-KumarH, I've got the same problem when I run it on Docker. What I did was in the requirements.txt, where I have celery==4.0.2, I put before amqp==2.1.4 and that was all.

**Comment by nbrgil** [comment]
I've got the same problem with airflow using celery: 

`[rgil@gfn-tix-2glv862 airflow]$ docker logs -f polos-flower
sed: cannot rename /airflow/seda5h0TL: Device or resource busy
Thu Jul 13 15:19:37 BRT 2017 - waiting for RabbitMQ... 1/10
Thu Jul 13 15:19:42 BRT 2017 - waiting for RabbitMQ... 2/10
HTTP/1.1 200 OK
[2017-07-13 15:19:48,159] {__init__.py:57} INFO - Using executor CeleryExecutor
[I 170713 15:19:49 command:139] Visit me at http://0.0.0.0:5555
[I 170713 15:19:49 command:144] Broker: amqp://airflow:**@airflowenv_rabbitmq_1:5672/airflow
[I 170713 15:19:49 command:147] Registered tasks: 
    ['celery.accumulate',
     'celery.backend_cleanup',
     'celery.chain',
     'celery.chord',
     'celery.chord_unlock',
     'celery.chunks',
     'celery.group',
     'celery.map',
     'celery.starmap']
[E 170713 15:19:49 events:123] Failed to capture events: 'Can't convert 'bytes' object to str implicitly', trying again in 2 seconds.
`
I had to freeze the amqp==2.1.4 to fix for now.

**Comment by thedrow** [comment]
@wooyek @lcd1232 @Arun-KumarH @erinaceous I released 2.2.1. Please verify it works for you guys.

**Comment by lcd1232** [comment]
@thedrow yes, all works. Thanks.

**Comment by thedrow** [comment]
I'll continue with the release over the weekend. Thanks.

**Comment by so2bin** [comment]
@thedrow thanks ,.....
