### ISSUE TITLE
How should I handle 

### ISSUE THREAD

**Issue by cenkalti** [celery/py-amqp#186]

**Comment by cenkalti** [comment]
`drain_events` function normally raises `socket.timeout()` when there is no event in `timeout` period. But sometimes I see the previous traceback in logs. AFAIK Python socket module raises `socket.timeout()` too when there is no data to be received. I can reproduce that with a simple script.

However, I can't reproduce the case that `drain_events` throwing `TimeoutError`.

Does this exception needs to be handled by the library or my application code?

Using Python 3.5 on Linux.

**Comment by cenkalti** [comment]
After some investigation I found out that `TimeoutError` is specifically a subclass of OSError representing the case where `errno` is `ETIMEDOUT`: https://bugs.python.org/issue21376#msg217402

In Linux, `ETIMEDOUT` is set by operating system if TCP keep-alive mechanism detects that the connection is dead: http://man7.org/linux/man-pages/man7/tcp.7.html

I have found that there are some default options that is set on the socket about TCP keep-alive feature starting from version 2.1.4: https://amqp.readthedocs.io/en/latest/changelog.html#version-2-1-4

These parameters are defined here in code: https://github.com/celery/py-amqp/blob/068223d25167ab63735158a7083946971308fce2/amqp/transport.py#L36-L42

I think `TCP_USER_TIMEOUT` parameter here is set to very low value (1 second). I propose increasing this value to at least 10 seconds. What do you think?

**Comment by jenstroeger** [comment]
@cenkalti, I see the same issue when using a Celery [`ResultGroup`](http://docs.celeryproject.org/en/latest/reference/celery.result.html#celery.result.GroupResult) with several tasks, and then attempting to [`revoke()`](http://docs.celeryproject.org/en/latest/reference/celery.result.html#celery.result.ResultSet.revoke) the group.

Did changing the TCP timeout solve this?

**Comment by cenkalti** [comment]
@jenstroeger No, changing the `TCP_USER_TIMEOUT` didn't solve the problem, we keep seeing `TimeoutError` exceptions.

**Comment by jenstroeger** [comment]
@cenkalti, hmmm… ok 🤔I guess I’ll switch to plan B then and revoke all tasks of the group individually, while digging for the root cause of the timeout on our side. Thanks!

**Comment by edvm** [comment]
Here having the same error:

```
Traceback (most recent call last):
  File "/home/emarcozzi/env/lib64/python3.6/site-packages/kombu/messaging.py", line 181, in publish
    exchange_name, declare,
  File "/home/emarcozzi/env/lib64/python3.6/site-packages/kombu/messaging.py", line 203, in _publish
    mandatory=mandatory, immediate=immediate,
  File "/home/emarcozzi/env/lib64/python3.6/site-packages/amqp/channel.py", line 1766, in _basic_publish
    (0, exchange, routing_key, mandatory, immediate), msg
  File "/home/emarcozzi/env/lib64/python3.6/site-packages/amqp/abstract_channel.py", line 59, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/home/emarcozzi/env/lib64/python3.6/site-packages/amqp/method_framing.py", line 172, in write_frame
    write(view[:offset])
  File "/home/emarcozzi/env/lib64/python3.6/site-packages/amqp/transport.py", line 305, in write
    self._write(s)
TimeoutError: [Errno 110] Connection timed out
```

Using `amqp==2.6.0`, and here is the code that (after pushing aprox 1 millon packages) raise the exception:

```python
def run():
    with Connection(rabbit_url, read_timeout=30000, write_timeout=30000) as conn:
        with open("foo.csv", "r") as fp:
            exchange = Exchange("example-exchange-1", type="direct")
            channel = conn.channel()
            producer = Producer(exchange=exchange, channel=channel, routing_key="test")
            queue = Queue(name="test-1", exchange=exchange, routing_key="test")
            queue.maybe_bind(conn)
            queue.declare()
            for line in fp:
                producer.publish(line, max_retries=3, errback=lambda x: print(x))

```

**Comment by WZhijun154** [comment]
any updates on this problem?
```
pip list | grep amqp
amqp                                     5.3.1
```
```
Traceback (most recent call last):
  File "/root/test/amqp_test.py", line 106, in <module>
    consumer()
  File "/root/test/amqp_test.py", line 64, in consumer
    connection.connect()
  File "/usr/local/lib/python3.10/dist-packages/amqp/connection.py", line 330, in connect
    self.drain_events(timeout=self.connect_timeout)
  File "/usr/local/lib/python3.10/dist-packages/amqp/connection.py", line 526, in drain_events
    while not self.blocking_read(timeout):
  File "/usr/local/lib/python3.10/dist-packages/amqp/connection.py", line 531, in blocking_read
    frame = self.transport.read_frame()
  File "/usr/local/lib/python3.10/dist-packages/amqp/transport.py", line 297, in read_frame
    frame_header = read(7, True)
  File "/usr/local/lib/python3.10/dist-packages/amqp/transport.py", line 577, in _read
    s = recv(n - len(rbuf))  # see note above
  File "/usr/lib/python3.10/ssl.py", line 1161, in read
    return self._sslobj.read(len)
TimeoutError: The read operation timed out

```
