### ISSUE TITLE
pyamqp transport is not thread-safe

### ISSUE THREAD

**Issue by jimbobhickville** [celery/py-amqp#267]
When talking to rabbitmq, you need to use a different channel_id per thread. The pyamp transport does not do this and always reuses channel_id 1 for all threads within a process. This results in a lot of silent failures where no exceptions are raised, but messages fail to be published or consumed.

I have locally monkey-patched the Channel object to force a unique channel id per active thread, and it seems to solve the problem I was running into without causing any issues:

```
import threading
from kombu.transport import pyamqp


class ThreadSafeChannel(pyamqp.Channel):
    def __init__(self, connection, channel_id=None, **kwargs):
        if channel_id is None and threading.current_thread() != threading.main_thread():
            # force it to get a unique channel_id per thread
            channel_id = threading.get_ident() % connection.channel_max
        super().__init__(connection, channel_id=channel_id, **kwargs)


def make_kombu_threadsafe():
    pyamqp.Connection.Channel = ThreadSafeChannel
```

I'm happy to port that to kombu proper and submit a PR, but thought I'd make sure that such a change would be welcome before I spend the effort doing so.

**Comment by thedrow** [comment]
This actually belongs to py-amqp itself.
We can definitely add this code.

It seems sensible.

**Comment by thedrow** [comment]
Are you sure that's the case?
Seems like we pick a new channel id every time we create a channel:
https://github.com/celery/py-amqp/blob/938f8a34bc6608d9b8889958828ea2d96ebdf8ed/amqp/connection.py#L466

**Comment by thedrow** [comment]
I'm pretty sure your solution does not make py-amqp threadsafe since we don't specify which channel to use.

When I try to close a connection after multiple channels have been created in different threads I get the following exception:

```
Traceback (most recent call last):
  File "/home/omer/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/omer/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/omer/Documents/Projects/py-amqp/t/integration/test_rmq.py", line 158, in worker
    connection.channel()
  File "/home/omer/Documents/Projects/py-amqp/amqp/connection.py", line 498, in channel
    channel.open()
  File "/home/omer/Documents/Projects/py-amqp/amqp/channel.py", line 437, in open
    spec.Channel.Open, 's', ('',), wait=spec.Channel.OpenOk,
  File "/home/omer/Documents/Projects/py-amqp/amqp/abstract_channel.py", line 60, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "/home/omer/Documents/Projects/py-amqp/amqp/abstract_channel.py", line 80, in wait
    self.connection.drain_events(timeout=timeout)
  File "/home/omer/Documents/Projects/py-amqp/amqp/connection.py", line 516, in drain_events
    while not self.blocking_read(timeout):
  File "/home/omer/Documents/Projects/py-amqp/amqp/connection.py", line 521, in blocking_read
    frame = self.transport.read_frame()
  File "/home/omer/Documents/Projects/py-amqp/amqp/transport.py", line 266, in read_frame
    payload = read(size)
  File "/home/omer/Documents/Projects/py-amqp/amqp/transport.py", line 448, in _read
    raise IOError('Server unexpectedly closed connection')
OSError: Server unexpectedly closed connection

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/omer/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/omer/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/omer/Documents/Projects/py-amqp/t/integration/test_rmq.py", line 158, in worker
    connection.channel()
  File "/home/omer/Documents/Projects/py-amqp/amqp/connection.py", line 498, in channel
    channel.open()
  File "/home/omer/Documents/Projects/py-amqp/amqp/channel.py", line 437, in open
    spec.Channel.Open, 's', ('',), wait=spec.Channel.OpenOk,
  File "/home/omer/Documents/Projects/py-amqp/amqp/abstract_channel.py", line 60, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "/home/omer/Documents/Projects/py-amqp/amqp/abstract_channel.py", line 80, in wait
    self.connection.drain_events(timeout=timeout)
  File "/home/omer/Documents/Projects/py-amqp/amqp/connection.py", line 516, in drain_events
    while not self.blocking_read(timeout):
  File "/home/omer/Documents/Projects/py-amqp/amqp/connection.py", line 521, in blocking_read
    frame = self.transport.read_frame()
  File "/home/omer/Documents/Projects/py-amqp/amqp/transport.py", line 268, in read_frame
    ch = ord(read(1))
  File "/home/omer/Documents/Projects/py-amqp/amqp/transport.py", line 448, in _read
    raise IOError('Server unexpectedly closed connection')
OSError: Server unexpectedly closed connection
```

Both threads simply hang until the join times out...

**Comment by jimbobhickville** [comment]
Sorry for the delay in responding, I was on vacation and then forgot when I returned. So, it's possible this was a red herring. I was able to confirm that each thread was using the same channel id before. The `_get_free_channel_id` method was returning the first id from the array in each thread. I am not, however, sure that this was causing the actual problem that I was having. 

Each thread in my app needed 2 connections, so at 10 threads, they'd all establish the first connection and exhaust the pool, then the first thread would try to establish the 2nd connection and would hang indefinitely waiting on a connection to be released back to the pool. It is using blocking `acquire` for both producer and consumer:

```
with kombu.connections[self._conn].acquire(block=True) as conn:
```

The main problem I was having was that I was being forced to a 10 connection pool limit, despite the documentation specifying that the default behavior was no limit.

https://github.com/celery/kombu/blob/master/kombu/pools.py#L110
https://github.com/celery/kombu/blob/master/kombu/pools.py#L93-L94
https://github.com/celery/kombu/blob/master/kombu/pools.py#L125-L127
https://github.com/celery/kombu/blob/master/kombu/pools.py#L17

So it would have 10 blocking consumers, but no producers to send out the initial message that would trigger the responses that it was supposed to consume and nothing would be processed.

I ended up specifying a pool limit that allowed for 2 connections per thread and the issue went away:

```
from kombu import pools as kombu_pools
kombu_pools.set_limit(thread_limit * 2)
```

I didn't remove the monkey-patch because I was on a deadline and didn't want to introduce entropy. I never saw the issues @thedrow reported about closing connections.

**Comment by thedrow** [comment]
Wait so we're talking about different **connections** that were trying to use the same **channel id**?
That should be allowed. Bunny does the [same thing](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/channel_id_allocator.rb#L9).

So does pika:

https://github.com/pika/pika/blob/40c60a7f3b08b769e3160b7dc2e5e0ec41ebd9fa/pika/connection.py#L1652-L1665

What I tested was sharing a connection over different threads using different channels initialized in those threads.

I don't think your patch is a valid patch.

**Comment by ask** [comment]
Amqp connections are not thread safe.
You need to use one connection per thread.

Should not attempt to make channels thread safe, unless it is part of a larger plan.

**Comment by thedrow** [comment]
I do want to make channels threadsafe.
Can connections ever be threadsafe or should we raise an exception when it's being used from a different thread?

**Comment by jimbobhickville** [comment]
Ah, so each connection can have the same channel id as long as they're separate connections? Then you can probably close this ticket. It would be nice to fix the documentation that the default pool limit is 10, not infinite.

**Comment by ask** [comment]
I assume you mean “don’t” because it will have no practical benefit.

Even if you raise an exception in Connection when creating a channel, you would have to protect the socket and check for every single write.

If threads are sharing channels/connections they will crash soon enough as framing becomes corrupted.

The way to use threads with amqp is to have one thread reading/writing from the socket, and the rest of threads communicate with that thread via queue.Queue.

This is also how you get performance from a threading setup: if mutexes are used you will have threads but performance suffers.

**Comment by thedrow** [comment]
Bunny uses a mutex to protect writes but not reads.
I'll have to measure and see if it really degrades performance.

**Comment by matteius** [comment]
Could you use a futex instead?

**Comment by matteius** [comment]
I am a bit confused on hope one of you can bring some clarity to this, because if this is sharing a connection across threads which share the same global interpreter lock or GIL, then only one thread is ever running at once (unlike in prefork which uses multiprocessing and actually forks the process so each has their own GIL and can run in parallel).  So if only one thread can run at at time and they are pooling the same connection, whats the big deal?  Does or can the OS switch threads in the middle of write operations?  If so I could see that being an issue that a mutex could solve for writes, but for reads I am less sure of as those could take a while to get a result.   A separate question for clarity is can the same py-amqp connection be used for both reads and writes or do those have to be two sockets (this may just be me forgetting something about sockets)?

**Comment by thedrow** [comment]
It does switch threads during syscalls. That's the whole point.
