### ISSUE TITLE
Doesn't work with Python 3.7.4

### ISSUE THREAD

**Issue by shashidharrao** [celery/py-amqp#304]
Doesn't work with Python 3.7.4, 

DEBUG:boto:establishing HTTPS connection: host=s3.amazonaws.com, kwargs={'timeout': 70, 'port': 443}
DEBUG:boto:Proxy connection: CONNECT s3.amazonaws.com:443 HTTP/1.0

Traceback (most recent call last):
  File "./samlapi_formauth.py", line 233, in <module>
    buckets = s3conn.get_all_buckets()
  File "/usr/local/lib/python3.7/site-packages/boto/s3/connection.py", line 443, in get_all_buckets
    response = self.make_request('GET', headers=headers)
  File "/usr/local/lib/python3.7/site-packages/boto/s3/connection.py", line 671, in make_request
    retry_handler=retry_handler
  File "/usr/local/lib/python3.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/usr/local/lib/python3.7/site-packages/boto/connection.py", line 913, in _mexe
    self.is_secure)
  File "/usr/local/lib/python3.7/site-packages/boto/connection.py", line 705, in get_http_connection
    return self.new_http_connection(host, port, is_secure)
  File "/usr/local/lib/python3.7/site-packages/boto/connection.py", line 747, in new_http_connection
    connection = self.proxy_ssl(host, is_secure and 443 or 80)
  File "/usr/local/lib/python3.7/site-packages/boto/connection.py", line 844, in proxy_ssl
    sslSock = http_client.ssl.SSLSocket(sock)
  File "/usr/lib64/python3.7/ssl.py", line 808, in __init__
    f"{self.__class__.__name__} does not have a public "
TypeError: SSLSocket does not have a public constructor. Instances are returned by SSLContext.wrap_socket().

**Comment by matusvalo** [comment]
@shashidharrao the stack trace provided in your comment are not from py-amqp library.
