### ISSUE TITLE
heartbeat timeouts since recent changes

### ISSUE THREAD

**Issue by jbg** [celery/py-amqp#31]
Since the recent (ca. Jan 10 or so) heartbeat changes, the following occurs often (maybe 75% of the time) when attempting to publish using Kombu and py-amqp:

```
Traceback (most recent call last):
  File "/home/...", line 430, in ...
    publish('...', {'ack': ..., 'result': result}, routing_key=reply_to)
  File "/home/...", line 109, in publish
    maybe_declare(exchange, producer.channel)
  File "/home/.../kombu/kombu/common.py", line 91, in maybe_declare
    return _maybe_declare(entity)
  File "/home/.../kombu/kombu/common.py", line 106, in _maybe_declare
    entity.declare()
  File "/home/.../kombu/kombu/entity.py", line 166, in declare
    nowait=nowait, passive=passive,
  File "/home/.../py-amqp/amqp/channel.py", line 613, in exchange_declare
    self._send_method((40, 10), args)
  File "/home/.../py-amqp/amqp/abstract_channel.py", line 56, in _send_method
    self.channel_id, method_sig, args, content,
  File "/home/.../py-amqp/amqp/method_framing.py", line 221, in write_method
    write_frame(1, channel, payload)
  File "/home/.../py-amqp/amqp/transport.py", line 163, in write_frame
    frame_type, channel, size, payload, 0xce,
ConnectionResetError: [Errno 104] Connection reset by peer
```

RabbitMQ logs this:

```
=ERROR REPORT==== 21-Jan-2014::07:30:53 ===
closing AMQP connection <0.29065.28> ([2401:F000:10:0:xxx]:39688 -> [2401:F000:10:0:xxx]:5672):
{heartbeat_timeout,running}
```

This publish is occurring from within a celery task body, if that makes any difference.

**Comment by taoqf** [comment]
I get this Error, too(Error 104)[https://github.com/celery/py-amqp/issues/122). but I do not use Celery, just py-amqp

**Comment by trianglesis** [comment]
Having the same on 4.2.0
