### ISSUE TITLE
consumer: Connection to broker lost. Trying to re-establish the connection...

### ISSUE THREAD

**Issue by girijesh97** [celery/py-amqp#322]
Hi,
I am using celery with my Django Application and I am facing connection error while executing a task for a longer time (approximately 10-15 mins). Though the connection is not getting broken for a shorter process.  Error log 

```
[2020-05-19 08:33:35,254: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/connection.py", line 494, in channel
    return self.channels[channel_id]
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/celery/worker/consumer/mingle.py", line 40, in start
    self.sync(c)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/celery/worker/consumer/mingle.py", line 44, in sync
    replies = self.send_hello(c)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/celery/worker/consumer/mingle.py", line 57, in send_hello
    replies = inspect.hello(c.hostname, our_revoked._data) or {}
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/celery/app/control.py", line 154, in hello
    return self._request('hello', from_node=from_node, revoked=revoked)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/celery/app/control.py", line 106, in _request
    pattern=self.pattern, matcher=self.matcher,
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/celery/app/control.py", line 480, in broadcast
    limit, callback, channel=channel,
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/kombu/pidbox.py", line 333, in _broadcast
    chan = channel or self.connection.default_channel
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/kombu/connection.py", line 870, in default_channel
    self._default_channel = self.channel()
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/kombu/connection.py", line 288, in channel
    chan = self.transport.create_channel(self.connection)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 100, in create_channel
    return connection.channel()
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/connection.py", line 497, in channel
    channel.open()
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/channel.py", line 435, in open
    spec.Channel.Open, 's', ('',), wait=spec.Channel.OpenOk,
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/abstract_channel.py", line 68, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/abstract_channel.py", line 88, in wait
    self.connection.drain_events(timeout=timeout)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/connection.py", line 505, in drain_events
    while not self.blocking_read(timeout):
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/connection.py", line 511, in blocking_read
    return self.on_inbound_frame(frame)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/method_framing.py", line 79, in on_frame
    callback(channel, msg.frame_method, msg.frame_args, msg)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/connection.py", line 518, in on_inbound_method
    method_sig, payload, content,
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/abstract_channel.py", line 145, in dispatch_method
    listener(*args)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/channel.py", line 1615, in _on_basic_deliver
    fun(msg)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/kombu/messaging.py", line 624, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/kombu/messaging.py", line 590, in receive
    [callback(body, message) for callback in callbacks]
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/kombu/messaging.py", line 590, in <listcomp>
    [callback(body, message) for callback in callbacks]
  File "/mnt/z/womble_backend/ml_app/TextAnalysis/tasks.py", line 85, in handle_message
    message.ack()
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/kombu/message.py", line 126, in ack
    self.channel.basic_ack(self.delivery_tag, multiple=multiple)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/channel.py", line 1394, in basic_ack
    spec.Basic.Ack, argsig, (delivery_tag, multiple),
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/abstract_channel.py", line 59, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/method_framing.py", line 172, in write_frame
    write(view[:offset])
  File "/home/ubuntu/.venv/textEnv/lib/python3.6/site-packages/amqp/transport.py", line 284, in write
    self._write(s)
ConnectionResetError: [Errno 104] Connection reset by peer
```
Although connection is getting restablished. I tried various methods to resolve the issue as it has been mentioned in other issue on this repo like setting `broker_hearbeat = None`, `amqp_task_result_expires = 30000` and running celery by using 
`celery -A MyApp worker -l info --without-heartbeat` but nothing work out for me.

I am stuck at this error for quite some time. Any help would be highly appreciated.

The version of the libraries I am using are as follows:

```
amqp==2.5.2
celery==4.4.2
Django==1.11.26
kombu==4.6.8
```

**Comment by matusvalo** [comment]
@girijesh97 not sure if I can help you just from information you have provided. Is this behavior repeatable or has only random occurrence? Can you provide some minimal example, where this issue can be reproduced? Moreover, I would recommend to you to check:
1. if this problem occurs also on master
2. if this problem occurs also in older releases maybe which release is the latest working.

Providing this information, would help us to pin down the issue.

**Comment by girijesh97** [comment]
@matusvalo Somehow I was able to solve the issue based on some speculation but I don't know if my solution is relevant or not. Here is the solution.
Initially, I was publishing several messages in a very small time frame. So I thought to introduce a sleep of 1 sec before publishing the next message. And fortunately, the error was resolved by doing so. It may sound very weird but just by doing this my error was resolved

**Comment by skilleton819** [comment]
Did the same 

> @matusvalo Somehow I was able to solve the issue based on some speculation but I don't know if my solution is relevant or not. Here is the solution. Initially, I was publishing several messages in a very small time frame. So I thought to introduce a sleep of 1 sec before publishing the next message. And fortunately, the error was resolved by doing so. It may sound very weird but just by doing this my error was resolved
