### ISSUE TITLE
Requirements conflict between amqp and vine

### ISSUE THREAD

**Issue by jaxzon** [celery/py-amqp#340]
Error while installing requirements: 
ERROR: amqp 2.6.1 has requirement vine<5.0.0a1,>=1.1.3, but you'll have vine 5.0.0 which is incompatible.

Partial list of requirements:
celery[redis]==4.3.0
celery-singleton==0.2.0
python-redis-lock==3.3.1
kombu==4.5.0
Django==2.2.1
python-jose==3.2.0

Which is causing:
```
out: Traceback (most recent call last):
out:   File "/app/settings/__init__.py", line 6, in <module>
out:     from settings.local import *
out:   File "/app/settings/local.py", line 1, in <module>
out:     from settings.staging import *
out:   File "/app/settings/staging.py", line 1, in <module>
out:     from settings.base import *
out:   File "/app/settings/base.py", line 16, in <module>
out:     from celery.schedules import crontab
out:   File "/usr/local/lib/python3.7/site-packages/celery/__init__.py", line 153, in <module>
out:     from . import local  # noqa
out:   File "/usr/local/lib/python3.7/site-packages/celery/local.py", line 17, in <module>
out:     from .five import PY3, bytes_if_py2, items, string, string_t
out:   File "/usr/local/lib/python3.7/site-packages/celery/five.py", line 7, in <module>
out:     import vine.five
out: ModuleNotFoundError: No module named 'vine.five'
```
Not sure is it kombu's issue or amqp...
EDIT - **Solution** which fixed my case:
Added fixed version upfront to my apps requirements:
amqp==2.6.0

**Comment by thedrow** [comment]
You shouldn't use 5.0.0 if you're not using Celery 5.0.0.

I've installed `amqp==2.6.1` myself and this is the result:
```
pip install 'amqp==2.6.1'
Collecting amqp==2.6.1
  Using cached amqp-2.6.1-py2.py3-none-any.whl (48 kB)
Collecting vine<5.0.0a1,>=1.1.3
  Using cached vine-1.3.0-py2.py3-none-any.whl (14 kB)
Installing collected packages: vine, amqp
Successfully installed amqp-2.6.1 vine-1.3.0
```

I'm not sure how you got that result.
In any case, this is not a bug or rather not a reproducible one if it is a bug.

**Comment by vigneshprasad** [comment]
Thanks for putting up a fix so quickly! 👍 Really appreciate it!

**Comment by thedrow** [comment]
> Thanks for putting up a fix so quickly! +1 Really appreciate it!

I... didn't fix anything but sure. No problem. :smile:

**Comment by jaxzon** [comment]
> > Thanks for putting up a fix so quickly! +1 Really appreciate it!
> 
> I... didn't fix anything but sure. No problem.

Quickfix is in my initial post.

**Comment by thedrow** [comment]
But there's nothing wrong as I demonstrated.

**Comment by ActionScripted** [comment]
Ran a test deploy and hit this same error. Fixed by explicitly installing amqp==2.6.1 which brings along vine. Not sure what changed -- our deploy code didn't -- but something did along the chain of dependencies.

**Comment by stickperson** [comment]
I'm seeing the same problem. 

```
(venv) circleci@<host>:~/circleci-demo-python-django$ pip freeze | grep -E 'amqp|celery|kombu'
amqp==2.6.1
celery==4.3.0
kombu==4.6.3
(venv) circleci@<host>:~/circleci-demo-python-django$ pip check
amqp 2.6.1 has requirement vine<5.0.0a1,>=1.1.3, but you have vine 5.0.0.
(venv) circleci@<host>:~/circleci-demo-python-django$ pip install amqp==2.6.1
Looking in indexes: https://pypi.org/simple
Requirement already satisfied: amqp==2.6.1 in ./venv/lib/python3.6/site-packages (2.6.1)
Collecting vine<5.0.0a1,>=1.1.3 (from amqp==2.6.1)
  Downloading https://files.pythonhosted.org/packages/7f/60/82c03047396126c8331ceb64da1dc52d4f1317209f32e8fe286d0c07365a/vine-1.3.0-py2.py3-none-any.whl
Installing collected packages: vine
  Found existing installation: vine 5.0.0
    Uninstalling vine-5.0.0:
      Successfully uninstalled vine-5.0.0
Successfully installed vine-1.3.0
You are using pip version 18.1, however version 20.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(venv) circleci@<host>:~/circleci-demo-python-django$ pip check
No broken requirements found.
```

**Comment by thedrow** [comment]
Oh I see. So this is a problem for users of 4.3?

**Comment by thedrow** [comment]
I just released 4.3.1 which addresses the problem. You are all welcome to upgrade.

**Comment by LECbg** [comment]
Hello, I know this is already fixed, but I'm trying to understand what's happening with my requirements.
Excuse my ignorance, but I don't get why `vine 5.0.0` got installed, could anyone explain me?

This is my `pipdeptree` output (excerpt of just Celery stuff, obviously, there's no other place where `vine` is mentioned):
```
flower==0.9.3
  - babel [required: >=1.0,<3.0.0, installed: 2.8.0]
    - pytz [required: >=2015.7, installed: 2019.1]
  - celery [required: >=3.1.0, installed: 4.3.0]
    - billiard [required: >=3.6.0,<4.0, installed: 3.6.3.0]
    - kombu [required: >=4.4.0,<5.0, installed: 4.6.11]
      - amqp [required: >=2.6.0,<2.7, installed: 2.6.1]
        - vine [required: >=1.1.3,<5.0.0a1, installed: 5.0.0]        <-- vine
      - importlib-metadata [required: >=0.18, installed: 1.7.0]
        - zipp [required: >=0.5, installed: 3.1.0]
    - pytz [required: >dev, installed: 2019.1]
    - vine [required: >=1.3.0, installed: 5.0.0]                     <-- vine
  - pytz [required: Any, installed: 2019.1]
  - tornado [required: >=4.2.0,<6.0.0, installed: 5.1.1]
```
`Celery`'s `vine` requirement (>=1.3.0) would accept 1.3.0, which would also satisfy `amqp`'s `>=1.1.3,<5.0.0a1`. I don't get why `5.0.0` gets installed.

As expected, `pip check` shows the following:
```
# pip check
amqp 2.6.1 has requirement vine<5.0.0a1,>=1.1.3, but you have vine 5.0.0.
```

Of those packages above, I only have fixed versions in my requirements files of the following:
```
flower==0.9.3
pytz==2019.1
celery==4.3.0
```

Thanks in advance.

**Comment by thedrow** [comment]
It might be a bug in pip?

**Comment by zeenfaizpy** [comment]
while installing add --use-feature=2020-resolver option

Pip shows following warning

```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

amqp 2.6.1 requires vine<5.0.0a1,>=1.1.3, but you'll have vine 5.0.0 which is incompatible.
```

**Comment by thedrow** [comment]
@zeenfaizpy This is definitely a bug in pip's resolver.
We should file a bug report.

**Comment by LECbg** [comment]
I updated to 4.3.1 and the problem got fixed as I mentioned back in September, but I recently got this error back and I don't know why. Here's my `pipdeptree` output:
```
flower==0.9.3
  - babel [required: >=1.0,<3.0.0, installed: 2.8.0]
    - pytz [required: >=2015.7, installed: 2019.1]
  - celery [required: >=3.1.0, installed: 4.3.1]
    - billiard [required: >=3.6.0,<4.0, installed: 3.6.3.0]
    - kombu [required: >=4.4.0,<5.0, installed: 4.6.11]
      - amqp [required: >=2.6.0,<2.7, installed: 2.6.1]
        - vine [required: >=1.1.3,<5.0.0a1, installed: 1.3.0]
      - importlib-metadata [required: >=0.18, installed: 2.0.0]
        - zipp [required: >=0.5, installed: 3.3.1]
    - pytz [required: >dev, installed: 2019.1]
    - vine [required: >=1.3.0,<5.0.0, installed: 1.3.0]
  - pytz [required: Any, installed: 2019.1]
  - tornado [required: >=4.2.0,<6.0.0, installed: 5.1.1]
```
The error traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 64, in _run_checks
    issues = run_checks(tags=[Tags.database])
  File "/usr/local/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.7/site-packages/django/core/checks/database.py", line 9, in check_database_backends
    for conn in connections.all():
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 216, in all
    return [self[alias] for alias in self]
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 213, in __iter__
    return iter(self.databases)
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 147, in databases
    self._databases = settings.DATABASES
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/config/__init__.py", line 3, in <module>
    from .celery_app import app as celery_app
  File "/app/config/celery_app.py", line 2, in <module>
    from celery import Celery
  File "/usr/local/lib/python3.7/site-packages/celery/__init__.py", line 153, in <module>
    from . import local  # noqa
  File "/usr/local/lib/python3.7/site-packages/celery/local.py", line 17, in <module>
    from .five import PY3, bytes_if_py2, items, string, string_t
  File "/usr/local/lib/python3.7/site-packages/celery/five.py", line 7, in <module>
    import vine.five
ModuleNotFoundError: No module named 'vine.five'
```
I'm using Python 3.7.9 and added the flag `--use-feature=2020-resolver` while installing with `pip`. 

Does anyone know what am I doing wrong?

Thank you.
