### ISSUE TITLE
Version 5.0.4 has an error

### ISSUE THREAD

**Issue by vadym-serdiuk** [celery/py-amqp#351]
Hi! 
The version 5.0.4 made our build failed.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/compilemessages.py", line 73, in handle
    basedirs.extend(settings.LOCALE_PATHS)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/app/__init__.py", line 3, in <module>
    from .celery import app as celery_app
  File "/app/app/celery.py", line 4, in <module>
    from celery import Celery
  File "/usr/local/lib/python3.8/site-packages/celery/local.py", line 491, in __getattr__
    module = __import__(self._object_origins[name], None, None,
  File "/usr/local/lib/python3.8/site-packages/celery/app/__init__.py", line 2, in <module>
    from celery import _state
  File "/usr/local/lib/python3.8/site-packages/celery/_state.py", line 15, in <module>
    from celery.utils.threads import LocalStack
  File "/usr/local/lib/python3.8/site-packages/celery/utils/__init__.py", line 6, in <module>
    from kombu.utils.objects import cached_property
  File "/usr/local/lib/python3.8/site-packages/kombu/utils/__init__.py", line 4, in <module>
    from .compat import fileno, maybe_fileno, nested, register_after_fork
  File "/usr/local/lib/python3.8/site-packages/kombu/utils/compat.py", line 16, in <module>
    from kombu.exceptions import reraise
  File "/usr/local/lib/python3.8/site-packages/kombu/exceptions.py", line 5, in <module>
    from amqp import ChannelError, ConnectionError, ResourceError
  File "/usr/local/lib/python3.8/site-packages/amqp/__init__.py", line 42, in <module>
    from .types import ChannelT, ConnectionT, MessageT
  File "/usr/local/lib/python3.8/site-packages/amqp/types.py", line 13, in <module>
    from .spec import method_sig_t
ImportError: cannot import name 'method_sig_t' from 'amqp.spec' (/usr/local/lib/python3.8/site-packages/amqp/spec.py)
```

Python 3.8
Django 3.1.5
Celery 5.0.5
Docker image: python:3.8

**Comment by kentuck13** [comment]
Same error.

**Comment by mintyPT** [comment]
Same

**Comment by voegtlel** [comment]
I wonder, aren't there any CI tests which would detect such kind of error? (I mean it already happens during importing the module)

**Comment by auvipy** [comment]
strange! sorry guys might messed with some commit in the release time

**Comment by auvipy** [comment]
fixing and releasing withing an hour

**Comment by auvipy** [comment]
Hi guys please check this https://pypi.org/project/amqp/5.0.5/

**Comment by auvipy** [comment]
really sorry guys for this. I m a terrible maintainer :(

**Comment by lithammer** [comment]
> really sorry guys for this. I m a terrible maintainer :(

Shit happens 🤷‍♂️ Everyone can make mistakes. At least you were quick to resolve the issue which makes you a good maintainer in my book.

**Comment by raphaelm** [comment]
> really sorry guys for this. I m a terrible maintainer :(

You're not! Without you, we'd need to all this ourselves. Thank you for your work.

:heart:

**Comment by jorrit-wehelp** [comment]
yeah, definitely not terrible :)
And https://github.com/celery/py-amqp/pull/352 should get the CI working again, might help prevent this in the future.

**Comment by flying-sheep** [comment]
You could yank the release, then nothing will accidentally install it.

**Comment by thedrow** [comment]
@auvipy Please yank the release ASAP. @flying-sheep is right :)

**Comment by auvipy** [comment]
> @auvipy Please yank the release ASAP. @flying-sheep is right :)

ok

**Comment by thedrow** [comment]
Just go to PyPi, check the list of versions and there will be a button next to the release to yank it.

**Comment by auvipy** [comment]
> Just go to PyPi, check the list of versions and there will be a button next to the release to yank it.

thanks, checked, but I only see that button on the packages to which I have admin access.

**Comment by thedrow** [comment]
Yanked.
