### ISSUE TITLE
Frames cease to be read while processing amqp_method.

### ISSUE THREAD

**Issue by w3iBStime** [celery/py-amqp#37]
While long-running message handlers (amqp_method) run, inbound frames need to continue to be processed in the background so that heartbeat frames (frame_type == 8) can continue to increment the bytes_recd attribute of the MethodReader and update the condition checks in connection.heartbeat_tick.

http://stackoverflow.com/questions/14817181/django-celery-connectionerror-too-many-heartbeats-missed

**Comment by adkl** [comment]
Hello guys,

I am currently trying to solve a similar problem as here and https://github.com/celery/kombu/issues/621. After some time spent debugging, I realized this is the exact cause of the `amqp.exceptions.ConnectionForced: Too many heartbeats missed` error. So yeah, I have long-running tasks in AMQP consumers but still want to receive server answers to the heartbeats I am sending through another thread.

I don't have deep knowledge of socket and thread programming in Python, but I am very very interested in how these things work.

So, I would really appreciate more detailed answers from some of the guys from `celery`.

Why is this impossible to achieve?
Why is it bad to read from a socket from two threads (Web server does the same?). In Python, we have GIL so it seems there is no need for locks and thread scheduling should do the job?

Here is my very simple example of code. Please help me understand why is this happening:

```
import logging
import sys
from threading import Thread
from time import sleep, time

from kombu import Connection, Exchange, Queue, Consumer
import socket
rabbit_url = "amqp://rabbitmq:rabbitmq@localhost:5672//"
conn = Connection(rabbit_url, heartbeat=5)
exchange = Exchange("example-exchange", type="direct")
queue = Queue(name="example-queue", exchange=exchange, routing_key="BOB")
logging.basicConfig(level=10, stream=sys.stdout)


def process_message(body, message):
    print("The body is {}\n".format(body))
    print("Processing message...\n")
    k = 10
    for i in range(0, 1000000000):
        if i % k == 0:
            k = k * 10
            print(i)
    print("Message processed!\n")
    message.ack()


consumer = Consumer(conn, queues=queue, callbacks=[process_message], accept=["text/plain"])
consumer.consume()


def establish_connection():
    revived_connection = conn.clone()
    revived_connection.ensure_connection(max_retries=3)
    channel = revived_connection.channel()
    consumer.revive(channel)
    consumer.consume()
    return revived_connection


def setup_heartbeats(conn: Connection, rate):
    while True:
        print("* DAEMON HEART BEAT STARTED *")
        start = time()
        conn.heartbeat_check()
        end = time()
        print("* DAEMON HEART BEAT ENDED IN *", (end - start)*1000, "ms")
        print('recv', conn.connection.last_heartbeat_received)
        print('sent', conn.connection.last_heartbeat_sent)
        sleep(rate)


def consume():
    rate = 1
    new_conn = establish_connection()
    heartbeats_t = Thread(target=setup_heartbeats, args=(new_conn, rate), daemon=True)
    heartbeats_t.start()
    while True:
        try:
            new_conn.drain_events(timeout=rate)
        except socket.timeout:
            pass


def run():
    while True:
        try:
            consume()
        except conn.connection_errors:
            print("connection revived")


run()
```

And here are the logs, very similar to the previous issue I've been referred to:

```
* DAEMON HEART BEAT ENDED IN * 2.932310104370117 ms
recv 18187.531
sent 18185.531
* DAEMON HEART BEAT STARTED *
DEBUG:amqp:heartbeat_tick : for connection e1c989e36229435491a361361efa3258
DEBUG:amqp:heartbeat_tick : Prev sent/recv: 10/13, now - 10/14, monotonic - 18189.546, last_heartbeat_sent - 18185.531, heartbeat int. - 5.0 for connection e1c989e36229435491a361361efa3258
* DAEMON HEART BEAT ENDED IN * 1.9519329071044922 ms
recv 18189.546
sent 18185.531
The body is EXAMPLE MESSAGE

Processing message...

0
100
1000
10000
100000
* DAEMON HEART BEAT STARTED *
DEBUG:amqp:heartbeat_tick : for connection e1c989e36229435491a361361efa3258
DEBUG:amqp:heartbeat_tick : Prev sent/recv: 10/14, now - 10/16, monotonic - 18190.546, last_heartbeat_sent - 18185.531, heartbeat int. - 5.0 for connection e1c989e36229435491a361361efa3258
DEBUG:amqp:heartbeat_tick: sending heartbeat for connection e1c989e36229435491a361361efa3258
* DAEMON HEART BEAT ENDED IN * 10.007619857788086 ms
recv 18190.546
sent 18190.562
1000000
* DAEMON HEART BEAT STARTED *
DEBUG:amqp:heartbeat_tick : for connection e1c989e36229435491a361361efa3258
DEBUG:amqp:heartbeat_tick : Prev sent/recv: 10/16, now - 11/16, monotonic - 18191.578, last_heartbeat_sent - 18191.578, heartbeat int. - 5.0 for connection e1c989e36229435491a361361efa3258
* DAEMON HEART BEAT ENDED IN * 10.001182556152344 ms
recv 18190.546
sent 18191.578
* DAEMON HEART BEAT STARTED *
DEBUG:amqp:heartbeat_tick : for connection e1c989e36229435491a361361efa3258
DEBUG:amqp:heartbeat_tick : Prev sent/recv: 11/16, now - 11/16, monotonic - 18192.609, last_heartbeat_sent - 18191.578, heartbeat int. - 5.0 for connection e1c989e36229435491a361361efa3258
* DAEMON HEART BEAT ENDED IN * 3.0205249786376953 ms
recv 18190.546
sent 18191.578
10000000
* DAEMON HEART BEAT STARTED *
DEBUG:amqp:heartbeat_tick : for connection e1c989e36229435491a361361efa3258
DEBUG:amqp:heartbeat_tick : Prev sent/recv: 11/16, now - 11/16, monotonic - 18193.625, last_heartbeat_sent - 18191.578, heartbeat int. - 5.0 for connection e1c989e36229435491a361361efa3258
* DAEMON HEART BEAT ENDED IN * 1.9998550415039062 ms
recv 18190.546
sent 18191.578
* DAEMON HEART BEAT STARTED *
DEBUG:amqp:heartbeat_tick : for connection e1c989e36229435491a361361efa3258
DEBUG:amqp:heartbeat_tick : Prev sent/recv: 11/16, now - 11/16, monotonic - 18194.656, last_heartbeat_sent - 18191.578, heartbeat int. - 5.0 for connection e1c989e36229435491a361361efa3258
* DAEMON HEART BEAT ENDED IN * 3.0167102813720703 ms
recv 18190.546
sent 18191.578
* DAEMON HEART BEAT STARTED *
DEBUG:amqp:heartbeat_tick : for connection e1c989e36229435491a361361efa3258
DEBUG:amqp:heartbeat_tick : Prev sent/recv: 11/16, now - 11/16, monotonic - 18195.671, last_heartbeat_sent - 18191.578, heartbeat int. - 5.0 for connection e1c989e36229435491a361361efa3258
* DAEMON HEART BEAT ENDED IN * 3.977060317993164 ms
recv 18190.546
sent 18191.578
* DAEMON HEART BEAT STARTED *
DEBUG:amqp:heartbeat_tick : for connection e1c989e36229435491a361361efa3258
DEBUG:amqp:heartbeat_tick : Prev sent/recv: 11/16, now - 11/16, monotonic - 18196.703, last_heartbeat_sent - 18191.578, heartbeat int. - 5.0 for connection e1c989e36229435491a361361efa3258
DEBUG:amqp:heartbeat_tick: sending heartbeat for connection e1c989e36229435491a361361efa3258
* DAEMON HEART BEAT ENDED IN * 14.022350311279297 ms
recv 18190.546
sent 18196.703
* DAEMON HEART BEAT STARTED *
DEBUG:amqp:heartbeat_tick : for connection e1c989e36229435491a361361efa3258
DEBUG:amqp:heartbeat_tick : Prev sent/recv: 11/16, now - 12/16, monotonic - 18197.734, last_heartbeat_sent - 18197.734, heartbeat int. - 5.0 for connection e1c989e36229435491a361361efa3258
* DAEMON HEART BEAT ENDED IN * 1.9764900207519531 ms
recv 18190.546
sent 18197.734
* DAEMON HEART BEAT STARTED *
DEBUG:amqp:heartbeat_tick : for connection e1c989e36229435491a361361efa3258
DEBUG:amqp:heartbeat_tick : Prev sent/recv: 12/16, now - 12/16, monotonic - 18198.75, last_heartbeat_sent - 18197.734, heartbeat int. - 5.0 for connection e1c989e36229435491a361361efa3258
* DAEMON HEART BEAT ENDED IN * 1.9772052764892578 ms
recv 18190.546
sent 18197.734
* DAEMON HEART BEAT STARTED *
DEBUG:amqp:heartbeat_tick : for connection e1c989e36229435491a361361efa3258
DEBUG:amqp:heartbeat_tick : Prev sent/recv: 12/16, now - 12/16, monotonic - 18199.765, last_heartbeat_sent - 18197.734, heartbeat int. - 5.0 for connection e1c989e36229435491a361361efa3258
* DAEMON HEART BEAT ENDED IN * 1.9998550415039062 ms
recv 18190.546
sent 18197.734
* DAEMON HEART BEAT STARTED *
DEBUG:amqp:heartbeat_tick : for connection e1c989e36229435491a361361efa3258
DEBUG:amqp:heartbeat_tick : Prev sent/recv: 12/16, now - 12/16, monotonic - 18200.781, last_heartbeat_sent - 18197.734, heartbeat int. - 5.0 for connection e1c989e36229435491a361361efa3258
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Users\Adnan\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\Adnan\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:/Users/Adnan/Code/Python/python-playground/main.py", line 44, in setup_heartbeats
    conn.heartbeat_check()
  File "C:\Users\Adnan\Code\kombu\kombu\connection.py", line 312, in heartbeat_check
    return self.transport.heartbeat_check(self.connection, rate=rate)
  File "C:\Users\Adnan\Code\kombu\kombu\transport\pyamqp.py", line 149, in heartbeat_check
    return connection.heartbeat_tick(rate=rate)
  File "C:\Users\Adnan\Code\Python\python-playground\venv\lib\site-packages\amqp\connection.py", line 749, in heartbeat_tick
    raise ConnectionForced('Too many heartbeats missed')
amqp.exceptions.ConnectionForced: Too many heartbeats missed
```
