### ISSUE TITLE
AMQP heartbeats fail

### ISSUE THREAD

**Issue by jbg** [celery/py-amqp#60]
With heartbeats enabled, the application crashes after a short time with the below stacktrace. I am not sure yet if this issue is with py-amqp, kombu or celery but am recording it here in the meantime.

```
 Traceback (most recent call last):
   File "/home/.../py-amqp/amqp/connection.py", line 561, in send_heartbeat
     self._frame_writer.send((8, 0, None, None, None))
 StopIteration
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/home/.../celery/celery/worker/consumer.py", line 278, in start
     blueprint.start(self)
   File "/home/.../celery/celery/bootsteps.py", line 123, in start
     step.start(parent)
   File "/home/.../celery/celery/worker/consumer.py", line 851, in start
     c.loop(*c.loop_args())
   File "/home/.../celery/celery/worker/loops.py", line 74, in asynloop
     next(loop)
   File "/home/.../kombu/kombu/async/hub.py", line 278, in create_loop
     poll_timeout = fire_timers(propagate=propagate) if scheduled else 1
   File "/home/.../kombu/kombu/async/hub.py", line 134, in fire_timers
     entry()
   File "/home/.../kombu/kombu/async/timer.py", line 63, in __call__
     return self.fun(*self.args, **self.kwargs)
   File "/home/.../kombu/kombu/async/timer.py", line 131, in _reschedules
     return fun(*args, **kwargs)
   File "/home/.../kombu/kombu/connection.py", line 264, in heartbeat_check
     return self.transport.heartbeat_check(self.connection, rate=rate)
   File "/home/.../kombu/kombu/transport/pyamqp.py", line 137, in heartbeat_check
     return connection.heartbeat_tick(rate=rate)
   File "/home/.../py-amqp/amqp/connection.py", line 586, in heartbeat_tick
     self.send_heartbeat()
   File "/home/.../py-amqp/amqp/connection.py", line 563, in send_heartbeat
     raise RecoverableConnectionError('connection already closed')
 amqp.exceptions.RecoverableConnectionError: connection already closed
```

RabbitMQ logs:
```
=WARNING REPORT==== 21-Dec-2014::14:01:51 ===
Non-AMQP exit reason '{exit,
{amqp_error,frame_error,
"cannot decode <<0,0,0,0,0,0>>",
'connection.close'},
'connection.close',
[{rabbit_misc,protocol_error,1,[]},
{rabbit_reader,handle_method0,3,[]},
{rabbit_reader,handle_input,3,[]},
{rabbit_reader,recvloop,4,[]},
{rabbit_reader,run,1,[]},
{rabbit_reader,start_connection,5,[]},
{proc_lib,init_p_do_apply,3,
[{file,"proc_lib.erl"},{line,237}]}]}'
```

The issue only occurs when heartbeats are enabled.

**Comment by ask** [comment]
Looks like this isn't a problem anymore, I tested it and at least the worker reconnects when this happens.
