### ISSUE TITLE
UnexpectedFrame exceptions when reading from queue

### ISSUE THREAD

**Issue by underyx** [celery/py-amqp#66]
We are seeing a bunch of these exceptions popping up when reading from a kombu `SimpleQueue`, under Python 3.4, with amqp 1.4.6 and kombu 3.0.26:

```
Traceback (most recent call last):
  [trimmed]
  File "/opt/virtualenvs/allmylespy/lib/python3.4/site-packages/allmylespy_common/rpc.py", line 156, in _get_reply
    reply = self._our_queue.get(block=True, timeout=1)
  File "/opt/virtualenvs/allmylespy/lib/python3.4/site-packages/kombu/simple.py", line 53, in get
    timeout=timeout and remaining)
  File "/opt/virtualenvs/allmylespy/lib/python3.4/site-packages/kombu/connection.py", line 275, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/opt/virtualenvs/allmylespy/lib/python3.4/site-packages/kombu/transport/pyamqp.py", line 95, in drain_events
    return connection.drain_events(**kwargs)
  File "/opt/virtualenvs/allmylespy/lib/python3.4/site-packages/amqp/connection.py", line 302, in drain_events
    chanmap, None, timeout=timeout,
  File "/opt/virtualenvs/allmylespy/lib/python3.4/site-packages/amqp/connection.py", line 365, in _wait_multiple
    channel, method_sig, args, content = read_timeout(timeout)
  File "/opt/virtualenvs/allmylespy/lib/python3.4/site-packages/amqp/connection.py", line 336, in read_timeout
    return self.method_reader.read_method()
  File "/opt/virtualenvs/allmylespy/lib/python3.4/site-packages/amqp/method_framing.py", line 189, in read_method
    raise m
  File "/opt/virtualenvs/allmylespy/lib/python3.4/site-packages/amqp/method_framing.py", line 107, in _next_method
    frame_type, channel, payload = read_frame()
  File "/opt/virtualenvs/allmylespy/lib/python3.4/site-packages/amqp/transport.py", line 175, in read_frame
    'Received 0x{0:02x} while expecting 0xce'.format(ch))
amqp.exceptions.UnexpectedFrame: Received 0x00 while expecting 0xce
```

I'd say between 0.01% and 0.5% of messages are affected. The error message varies, a few seconds earlier we had `Received 0x5e` instead. I see that 1.4.6 doesn't list Python 3.4 in its classifiers. Is it possibly incompatible? Are there any alternatives for Python 3?

**Comment by underyx** [comment]
Another exception which is almost certainly related:

```
Traceback (most recent call last):
  File "/opt/virtualenvs/allmylespy/lib/python3.4/site-packages/allmylespy_manager/epower/__init__.py", line 20, in send_request
    context, {'method': method, 'request': request}, timeout=CFG.gateway_timeout
  File "/opt/virtualenvs/allmylespy/lib/python3.4/site-packages/allmylespy_common/rpc.py", line 177, in handler
    return self._call_method(method, context, request, timeout)
  File "/opt/virtualenvs/allmylespy/lib/python3.4/site-packages/allmylespy_common/rpc.py", line 129, in _call_method
    reply = self._get_reply(message_id, timeout)
  File "/opt/virtualenvs/allmylespy/lib/python3.4/site-packages/allmylespy_common/rpc.py", line 156, in _get_reply
    reply = self._our_queue.get(block=True, timeout=1)
  File "/opt/virtualenvs/allmylespy/lib/python3.4/site-packages/kombu/simple.py", line 53, in get
    timeout=timeout and remaining)
  File "/opt/virtualenvs/allmylespy/lib/python3.4/site-packages/kombu/connection.py", line 275, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/opt/virtualenvs/allmylespy/lib/python3.4/site-packages/kombu/transport/pyamqp.py", line 95, in drain_events
    return connection.drain_events(**kwargs)
  File "/opt/virtualenvs/allmylespy/lib/python3.4/site-packages/amqp/connection.py", line 302, in drain_events
    chanmap, None, timeout=timeout,
  File "/opt/virtualenvs/allmylespy/lib/python3.4/site-packages/amqp/connection.py", line 365, in _wait_multiple
    channel, method_sig, args, content = read_timeout(timeout)
  File "/opt/virtualenvs/allmylespy/lib/python3.4/site-packages/amqp/connection.py", line 336, in read_timeout
    return self.method_reader.read_method()
  File "/opt/virtualenvs/allmylespy/lib/python3.4/site-packages/amqp/method_framing.py", line 189, in read_method
    raise m
  File "/opt/virtualenvs/allmylespy/lib/python3.4/site-packages/amqp/method_framing.py", line 107, in _next_method
    frame_type, channel, payload = read_frame()
  File "/opt/virtualenvs/allmylespy/lib/python3.4/site-packages/amqp/transport.py", line 157, in read_frame
    payload = read(size)
  File "/opt/virtualenvs/allmylespy/lib/python3.4/site-packages/amqp/transport.py", line 277, in _read
    s = recv(n - len(rbuf))
MemoryError
```

**Comment by ask** [comment]
Are you sure multiple threads are not using the same connection?

**Comment by ask** [comment]
Could you clean this up into multiple commits please? And why do we want to make the channel thread-safe?

**Comment by underyx** [comment]
@ask wrong issue?

**Comment by ask** [comment]
hmm, yeah, I guess, I wrote this comment on a pull request I'm pretty sure :/

**Comment by auvipy** [comment]
closing for lack of activity
